# Generated by Django 5.2.8 on 2025-11-20 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_alter_reciennacido_talla'),
    ]

    operations = [
        migrations.AddField(
            model_name='parto',
            name='alumbramiento_dirigido',
            field=models.BooleanField(blank=True, null=True, verbose_name='Alumbramiento dirigido'),
        ),
        migrations.AddField(
            model_name='parto',
            name='clasificacion_robson',
            field=models.CharField(blank=True, choices=[('grupo_1', 'Grupo 1'), ('grupo_2a', 'Grupo 2A'), ('grupo_2b', 'Grupo 2B'), ('grupo_3', 'Grupo 3'), ('grupo_4a', 'Grupo 4A'), ('grupo_4b', 'Grupo 4B'), ('grupo_5a', 'Grupo 5A'), ('grupo_5b', 'Grupo 5B'), ('grupo_6', 'Grupo 6'), ('grupo_7', 'Grupo 7'), ('grupo_8', 'Grupo 8'), ('grupo_10', 'Grupo 10')], max_length=20, null=True, verbose_name='Clasificación de Robson'),
        ),
        migrations.AddField(
            model_name='parto',
            name='induccion',
            field=models.BooleanField(blank=True, null=True, verbose_name='Inducción'),
        ),
        migrations.AddField(
            model_name='parto',
            name='monitor',
            field=models.BooleanField(blank=True, null=True, verbose_name='Monitor'),
        ),
        migrations.AddField(
            model_name='parto',
            name='paridad',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Paridad'),
        ),
        migrations.AddField(
            model_name='parto',
            name='semanas_obstetricas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Semanas Obstétricas'),
        ),
        migrations.AddField(
            model_name='parto',
            name='semanas_obstetricas_dias',
            field=models.IntegerField(blank=True, null=True, verbose_name='Semanas Obstétricas (días)'),
        ),
        migrations.AddField(
            model_name='parto',
            name='ttc',
            field=models.BooleanField(blank=True, null=True, verbose_name='TTC'),
        ),
        migrations.AlterField(
            model_name='parto',
            name='semanas_gestacion',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(45)]),
        ),
        migrations.AlterField(
            model_name='parto',
            name='tipo_anestesia',
            field=models.CharField(blank=True, choices=[('ninguna', 'Ninguna'), ('local', 'Local'), ('epidural', 'Epidural'), ('raquidea', 'Raquídea'), ('general', 'General')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='parto',
            name='tipo_parto',
            field=models.CharField(blank=True, choices=[('cesarea_urgencia', 'Cesárea Urgencia'), ('cesarea_electiva', 'Cesárea Electiva'), ('distocico', 'Distocico'), ('eutocico', 'Eutocico')], max_length=20, null=True, verbose_name='Tipo de Parto'),
        ),
    ]
