# Generated by Django 5.2.8 on 2025-11-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_parto_alumbramiento_dirigido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parto',
            name='acompanamiento_parto',
            field=models.BooleanField(blank=True, null=True, verbose_name='Acompañamiento Parto'),
        ),
        migrations.AddField(
            model_name='parto',
            name='acompanante_secciona_cordon',
            field=models.BooleanField(blank=True, null=True, verbose_name='Acompañante secciona cordón'),
        ),
        migrations.AddField(
            model_name='parto',
            name='motivo_parto_no_acompanado',
            field=models.TextField(blank=True, verbose_name='Motivo Parto NO acompañado'),
        ),
        migrations.AddField(
            model_name='parto',
            name='persona_acompanante',
            field=models.CharField(blank=True, choices=[('pareja', 'Pareja'), ('hermano', 'Hermana/o'), ('padre_madre', 'Padre/Madre'), ('tio', 'Tía/o'), ('suegro', 'Suegra/o')], max_length=20, null=True, verbose_name='Persona Acompañante'),
        ),
    ]
