# Generated by Django 5.2.8 on 2025-11-21 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_parto_acompanamiento_parto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parto',
            name='causa_cesarea',
            field=models.TextField(blank=True, verbose_name='Causa cesárea'),
        ),
        migrations.AddField(
            model_name='parto',
            name='profesional_a_cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partos_a_cargo', to=settings.AUTH_USER_MODEL, verbose_name='Profesional a cargo'),
        ),
    ]
