# Generated by Django 5.2.8 on 2025-11-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_parto_causa_cesarea_parto_profesional_a_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parto',
            name='profesional_a_cargo',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Profesional a cargo'),
            preserve_default=False,
        ),
    ]
