# Generated by Django 5.2.8 on 2025-11-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0007_alter_parto_profesional_a_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='parto',
            name='estampado_placenta',
            field=models.BooleanField(blank=True, null=True, verbose_name='Estampado de placenta'),
        ),
        migrations.AddField(
            model_name='parto',
            name='folio_valido',
            field=models.CharField(blank=True, max_length=100, verbose_name='Folio válido'),
        ),
        migrations.AddField(
            model_name='parto',
            name='folios_nulos',
            field=models.CharField(blank=True, max_length=200, verbose_name='Folio/s Nulo/s'),
        ),
        migrations.AddField(
            model_name='parto',
            name='ley_21372_dominga',
            field=models.TextField(blank=True, help_text='Cuales recuerdos (de no entregar justificar motivo)', verbose_name='Ley N° 21.372 Dominga'),
        ),
        migrations.AddField(
            model_name='parto',
            name='manejo_dolor_no_farmacologico',
            field=models.TextField(blank=True, verbose_name='Manejo del dolor no farmacológico'),
        ),
        migrations.AddField(
            model_name='parto',
            name='retira_placenta',
            field=models.BooleanField(blank=True, null=True, verbose_name='Retira placenta'),
        ),
        migrations.AddField(
            model_name='parto',
            name='uso_sala_saip',
            field=models.BooleanField(blank=True, null=True, verbose_name='Uso sala SAIP'),
        ),
    ]
