"""
Django settings for obstetricia project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

# Cargar variables de entorno desde un .env en desarrollo (opcional)
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read SECRET_KEY from environment for production safety. Fall back to the
# existing hard-coded key only for local development.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-7siveizwq8#a6%q9uxmf^2n8y9%=_m(xjexi07j(ubk+ud=#=d')

# SECURITY WARNING: don't run with debug turned on in production!
# Allow enabling/disabling DEBUG via env var (use '0' or 'False' for off).
# Default to False to avoid accidental debug in production environments.
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() not in ('0', 'false')

# Configure ALLOWED_HOSTS from environment (comma-separated)
ALLOWED_HOSTS = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h.strip()]

# Convenience: when debugging locally and no ALLOWED_HOSTS provided, allow localhost
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

# Fail-fast in production if ALLOWED_HOSTS is not configured. This avoids
# serving the site on an unexpected host and produces a clear error message.
if not DEBUG and not ALLOWED_HOSTS:
    raise RuntimeError('DJANGO_ALLOWED_HOSTS must be set when DEBUG is False')



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Apps locales
    'usuarios',
    'cuentas',
    'registros',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise sirve archivos estáticos de manera eficiente sin depender de
    # configuración adicional de servidor (útil en despliegues sencillos).
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'cuentas.middleware.AuditoriaMiddleware',
    # Middleware personalizado para control de sesión
    'cuentas.middleware.SessionTimeoutMiddleware',
]

ROOT_URLCONF = 'obstetricia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Expose a small flag to templates so they can show/hide signup links
                'cuentas.context_processors.signup_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'obstetricia.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

AUTH_USER_MODEL = "cuentas.Usuario"

import pymysql
pymysql.install_as_MySQLdb()
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "obstetricia",
        "USER": "root",
        "PASSWORD": "12345678",
        "HOST": "localhost",
        "PORT": "3306",
        "OPTIONS": {"charset": "utf8mb4"},
    }
}

# Allow configuring the database via a single `DATABASE_URL` env var (used by
# many PaaS providers like Render). If present, it will override the default
# DATABASES setting above.
if os.environ.get('DATABASE_URL'):
    DATABASES['default'] = dj_database_url.parse(os.environ.get('DATABASE_URL'), conn_max_age=600)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Usar WhiteNoise storage para servir archivos estáticos comprimidos y con
# cache busting en producción.
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
LOGIN_URL = '/login/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de Autenticación
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Configuraciones de autenticación
# Usar rutas (paths) para evitar problemas de reverse en middlewares y
# redirecciones internas. El dashboard principal está montado en '/'.
LOGIN_REDIRECT_URL = '/'  # después de login, ir al dashboard (root)
LOGIN_URL = '/login/'     # ruta pública de login
LOGOUT_REDIRECT_URL = '/login/'

# Si en el futuro se integra un sistema de terceros para signup (ej. allauth),
# agregar la configuración correspondiente aquí. Actualmente usamos el sistema
# de autenticación por defecto de Django.

# Configuraciones de Sesión
SESSION_COOKIE_AGE = 1200  # 20 minutos en segundos
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

